from sort_algorithms import sortAlgorithms
inst_sort_algorithms = sortAlgorithms()
inst_sort_algorithms.burble_sort_function()
inst_sort_algorithms.burble_sort_function_refactor()
inst_sort_algorithms.select_sort_function()
inst_sort_algorithms.insert_sort_function()
inst_sort_algorithms.merge_sort_function()