from binary_tree import BinaryTree
root = BinaryTree(35)
root.insert(root, BinaryTree(5))
root.insert(root, BinaryTree(20))
root.insert(root, BinaryTree(19))
root.insert(root, BinaryTree(42))
root.insert(root, BinaryTree(36))
root.insert(root, BinaryTree(31))
root.insert(root, BinaryTree(25))
root.insert(root, BinaryTree(30))
root.insert(root, BinaryTree(33))
root.insert(root, BinaryTree(101))
root.insert(root, BinaryTree(46))
root.insert(root, BinaryTree(29))
root.insert(root, BinaryTree(27))
root.insert(root, BinaryTree(98))
root.insert(root, BinaryTree(37))
root.insert(root, BinaryTree(16))
root.print_tree(root)